#!/usr/bin/env node
// @ts-nocheck
// Cross-platform script that generates android/local.properties and, when the
// system JDK is too new for Gradle (> 21), patches ~/.gradle/gradle.properties
// to redirect Gradle to the Android Studio bundled JBR.
//
// Usage:  node apps/patient-mobile/setup-android.mjs
//   or:   pnpm mobile:setup   (from the monorepo root)

import { spawnSync } from "child_process";
import fs from "fs";
import os from "os";
import path from "path";

const isWindows = process.platform === "win32";
const isMac = process.platform === "darwin";

// ─── Helpers ──────────────────────────────────────────────────────────────────

function exists(p) {
	return fs.existsSync(p);
}

// Properties files use backslash-escaped colons and backslashes.
// e.g.  C:\Users\foo\Sdk  →  C\:\\Users\\foo\\Sdk
function escapePropertiesValue(value) {
	return value.replace(/\\/g, "\\\\").replace(/:/g, "\\:");
}

// ─── Detect Android SDK ───────────────────────────────────────────────────────

function detectAndroidSdk() {
	const fromEnv = process.env.ANDROID_HOME ?? process.env.ANDROID_SDK_ROOT;
	if (fromEnv && exists(fromEnv)) {
		return fromEnv;
	}

	const defaults = isWindows
		? [path.join(process.env.LOCALAPPDATA ?? "", "Android", "Sdk")]
		: isMac
			? [path.join(os.homedir(), "Library", "Android", "sdk")]
			: [path.join(os.homedir(), "Android", "Sdk")];

	return defaults.find(exists) ?? null;
}

// ─── Detect JDK major version ─────────────────────────────────────────────────

function getJdkMajorVersion() {
	const result = spawnSync("java", ["-version"], { encoding: "utf8" });
	const output = (result.stderr ?? "") + (result.stdout ?? "");
	const match = output.match(/version "(\d+)/);
	return match ? parseInt(match[1], 10) : null;
}

// ─── Detect Android Studio JBR ───────────────────────────────────────────────

function detectAndroidStudioJbr() {
	const candidates = isWindows
		? ["C:\\Program Files\\Android\\Android Studio\\jbr"]
		: isMac
			? ["/Applications/Android Studio.app/Contents/jbr/Contents/Home"]
			: [path.join(os.homedir(), "android-studio", "jbr"), "/opt/android-studio/jbr"];

	return candidates.find(exists) ?? null;
}

// ─── main ─────────────────────────────────────────────────────────────────────

const androidDir = path.join(import.meta.dirname, "android");
const localPropsPath = path.join(androidDir, "local.properties");

// 1. Android SDK
const sdkPath = detectAndroidSdk();
if (!sdkPath) {
	console.error(
		"❌  Android SDK not found.\n" +
			"    Install Android Studio (https://developer.android.com/studio)\n" +
			"    or set the ANDROID_HOME environment variable and re-run this script."
	);
	process.exit(1);
}
console.log(`✅  Android SDK: ${sdkPath}`);

// 2. Write local.properties
const localPropsContent = `# Generated by setup-android.mjs — do not edit manually; re-run the script instead.
sdk.dir=${escapePropertiesValue(sdkPath)}
`;
fs.writeFileSync(localPropsPath, localPropsContent, "utf8");
console.log(`✅  Written: ${path.relative(process.cwd(), localPropsPath)}`);

// 3. JDK compatibility check
const jdkVersion = getJdkMajorVersion();
if (jdkVersion !== null && jdkVersion > 21) {
	console.warn(`⚠️   JDK ${jdkVersion} detected. Gradle requires JDK ≤ 21.`);

	const jbrPath = detectAndroidStudioJbr();
	if (!jbrPath) {
		console.error(
			"❌  Android Studio JBR not found.\n" +
				"    Install Android Studio, then re-run this script.\n" +
				"    Alternatively, add the following line to ~/.gradle/gradle.properties\n" +
				"    and point it at a JDK 17 or 21 installation:\n\n" +
				"      org.gradle.java.home=/path/to/jdk-21\n"
		);
		process.exit(1);
	}
	console.log(`✅  Android Studio JBR: ${jbrPath}`);

	// Write to ~/.gradle/gradle.properties — the only location Gradle honours
	// this setting from (local.properties is NOT read by Gradle for java.home).
	const gradleUserHome = process.env.GRADLE_USER_HOME ?? path.join(os.homedir(), ".gradle");
	const gradlePropsPath = path.join(gradleUserHome, "gradle.properties");

	const existing = exists(gradlePropsPath) ? fs.readFileSync(gradlePropsPath, "utf8") : "";

	if (existing.includes("org.gradle.java.home")) {
		console.log(`ℹ️   org.gradle.java.home already present in ${gradlePropsPath} — skipping.`);
	} else {
		fs.mkdirSync(gradleUserHome, { recursive: true });
		const jbrEscaped = isWindows ? escapePropertiesValue(jbrPath) : jbrPath;
		const addition =
			"\n# Added by cerios-clinic setup-android.mjs\n" +
			`# JDK ${jdkVersion} is too new for Gradle 8.x; use Android Studio JBR instead.\n` +
			`org.gradle.java.home=${jbrEscaped}\n`;
		fs.writeFileSync(gradlePropsPath, existing + addition, "utf8");
		console.log(`✅  Added org.gradle.java.home to ${gradlePropsPath}`);
	}
}

// 4. PATH check — platform-tools (adb) and emulator must be on PATH
const platformTools = path.join(sdkPath, "platform-tools");
const emulatorDir = path.join(sdkPath, "emulator");
const currentPath = process.env.PATH ?? "";
let pathWarnings = false;

if (!currentPath.includes(platformTools)) {
	console.warn(`⚠️   ${platformTools} is not in your PATH.`);
	console.warn("    adb commands will not work from the terminal.\n");
	pathWarnings = true;
}
if (!currentPath.includes(emulatorDir)) {
	console.warn(`⚠️   ${emulatorDir} is not in your PATH.`);
	console.warn("    The Android emulator will not be launchable from the terminal.\n");
	pathWarnings = true;
}

if (pathWarnings) {
	if (isWindows) {
		console.warn(
			"    Add both directories to your Windows User PATH:\n" +
				"    System Properties → Environment Variables → User Variables → Path → Edit\n" +
				`      ${platformTools}\n` +
				`      ${emulatorDir}\n` +
				"    Then restart your terminal.\n"
		);
	} else {
		const shellRc = isMac ? "~/.zshrc" : "~/.bashrc";
		console.warn(
			`    Add both directories to ${shellRc}:\n` +
				`      export PATH="$PATH:${platformTools}"\n` +
				`      export PATH="$PATH:${emulatorDir}"\n` +
				"    Then restart your terminal.\n"
		);
	}
} else {
	console.log("✅  PATH: platform-tools and emulator directories found.");
}

console.log("\n🚀  Android setup complete. You can now run: pnpm mobile:android\n");
