#!/usr/bin/env node
// @ts-nocheck
// Cross-platform script that generates apps/patient-mobile/.env for local
// release testing profiles.
//
// Usage:
//   node apps/patient-mobile/setup-env.mjs emulator
//   node apps/patient-mobile/setup-env.mjs lan
//   node apps/patient-mobile/setup-env.mjs lan --ip=192.168.1.42
//
// Optional environment variable for LAN profile:
//   MOBILE_LAN_IP=192.168.1.42

import fs from "fs";
import os from "os";
import path from "path";

const profile = (process.argv[2] ?? "emulator").toLowerCase();
const extraArgs = process.argv.slice(3);

if (profile !== "emulator" && profile !== "lan") {
	console.error(
		"Invalid profile. Use one of: emulator, lan\n" +
			"Examples:\n" +
			"  pnpm run mobile:env:emulator\n" +
			"  pnpm run mobile:env:lan\n" +
			"  pnpm run mobile:env:lan -- --ip=192.168.1.42\n"
	);
	process.exit(1);
}

const appDir = import.meta.dirname;
const envPath = path.join(appDir, ".env");

function isValidIpv4(ip) {
	const parts = ip.split(".");
	if (parts.length !== 4) return false;
	for (const part of parts) {
		if (!/^\d+$/.test(part)) return false;
		const n = Number(part);
		if (n < 0 || n > 255) return false;
	}
	return true;
}

function isPrivateIpv4(ip) {
	if (!isValidIpv4(ip)) return false;
	const [a, b] = ip.split(".").map(Number);
	return a === 10 || (a === 172 && b >= 16 && b <= 31) || (a === 192 && b === 168);
}

function detectLanIpv4() {
	const interfaces = os.networkInterfaces();
	for (const entries of Object.values(interfaces)) {
		if (!entries) continue;
		for (const item of entries) {
			if (item.family !== "IPv4") continue;
			if (item.internal) continue;
			if (!isPrivateIpv4(item.address)) continue;
			return item.address;
		}
	}
	return null;
}

function resolveHost() {
	if (profile === "emulator") {
		return "10.0.2.2";
	}

	const argIp = extraArgs.find(arg => arg.startsWith("--ip="))?.slice("--ip=".length);
	const ip = argIp ?? process.env.MOBILE_LAN_IP ?? detectLanIpv4();
	if (!ip || !isPrivateIpv4(ip)) {
		console.error(
			"Could not determine a private LAN IPv4 address.\n" +
				"Run with an explicit IP, for example:\n" +
				"  pnpm run mobile:env:lan -- --ip=192.168.1.42\n"
		);
		process.exit(1);
	}
	return ip;
}

const host = resolveHost();
const envContent = [
	"# Generated by setup-env.mjs",
	"API_URL=http://" + host + ":3001/api",
	"KEYCLOAK_URL=http://" + host + ":8180",
	"KEYCLOAK_REALM=clinic",
	"KEYCLOAK_CLIENT_ID=patient-mobile-client",
	"",
].join("\n");

fs.writeFileSync(envPath, envContent, "utf8");
console.log("Written " + path.relative(process.cwd(), envPath) + " for profile: " + profile + " (host: " + host + ")");

if (profile === "emulator") {
	console.log("Tip: use profile lan for physical devices on the same network.");
}
